name: Main

on: push

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install main
        run: |
          python -m pip install --upgrade pip
          python -m pip install -U black
      - name: Run main
        run: black .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
            commit_message: "Auto fixes"
            commit_options: "--no-verify"
            repository: .
            commit_user_name: campers98
            commit_user_email: 140605897+campers98@users.noreply.github.com
            commit_author: campers98 <campers98@users.noreply.github.com>
